Export mapLoggingT and mapNoLoggingT
snoyberg/monad-logger pull request #5
Opened 2018-08-01 02:51 UTC by mjrussell

As discussed in #4

2018-08-01 03:40 UTC, snoyberg requested changes
Can you:

* Add Haddocks to the exported functions
* Add a minor version bump to the package.yaml file
* Add a ChangeLog entry
* Add `@since` to the Haddocks for each newly exported function

2018-08-01 03:49 UTC, mjrussell commented
Done!I looked at the terminology in the other transformers:
`mapReaderT`: Transform the computation inside a ReaderT.
`mapIdentityT`: Lift a unary operation to the new monad.
`mapExceptT`: Map the unwrapped computation using the given function.

I was debating with how `mapExceptT` described it vs `mapReaderT`. Happy to change it.

2018-08-01 10:33 UTC, snoyberg requested changes
I'm fine with the wording, only change is to the version number.

2018-08-01 10:33 UTC, snoyberg commented on package.yaml
> +version:     0.3.28.6
The version bump should be to 0.3.29 to conform with the PVP.

2018-08-01 17:23 UTC, mjrussell commented on package.yaml
> +version:     0.3.28.6
Ah good call, fixed

2018-08-02 05:19 UTC, snoyberg approved these changes
Thanks!

2018-08-02 05:19 UTC, merged